[theme] # You have to add this line

primaryColor = '#FFBAF1' # Bright pink

backgroundColor = '#00325B' # Dark Blue

secondaryBackgroundColor = '#4D7CA3' # Lighter Blue

textColor = '#FFFFFF'

font = 'serif'
